services:
  db:
    image: 'postgres:14.1-alpine'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
#    volumes:
#      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  todo:
    image: ghcr.io/samitkumarpatel/todo:220820242049
    restart: on-failure
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/todo
      spring.datasource.username: user
      spring.datasource.password: secret
      spring.flyway.enabled: true