services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
#    volumes:
#      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql