@host = http://localhost:8080

### POST tags
POST {{host}}/todo/1/tags
Content-Type: application/json

{
  "name": "shopping"
}

### GET tags
GET {{host}}/todo/1/tags
Content-Type: application/json


### POST task
POST {{host}}/todo/1/tasks
Content-Type: application/json

{
  "title": "Buy grocery",
  "description": "Task 1",
  "date": "2025-05-11",
  "time": "00:00:15"
}

### POST task-2
POST {{host}}/todo/1/tasks
Content-Type: application/json

{
  "title": "Book Ticket",
  "description": "Task 2",
  "date": "2025-05-01",
  "time": "00:00:15"
}

### PATCH task
PATCH {{host}}/todo/1/tasks/1
Content-Type: application/json

{
  "tags": [
    {
      "tagId": 2
    }
  ]
}

### PATCH task COMPLETED
PATCH {{host}}/todo/1/tasks/2
Content-Type: application/json

{
  "status": "COMPLETED"
}

### GET task
GET {{host}}/todo/1/tasks/1
Content-Type: application/json

### DELETE tags
DELETE {{host}}/todo/1/tags/2

### GET notifications
GET {{host}}/todo/1/notification