services:
  db:
    image: 'postgres:14.1-alpine'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.hostname == samit-NUC

  todo:
    image: ghcr.io/samitkumarpatel/todo:220820242108
    restart: on-failure
    depends_on:
      - "db"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
      placement:
        constraints:
          - node.hostname == samit-NUC
    environment:
      spring.datasource.url: 'jdbc:postgresql://db:5432/todo'
      spring.datasource.username: 'user'
      spring.datasource.password: 'secret'
      spring.flyway.enabled: 'true'