services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=todo'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql