name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    uses: samitkumarpatel/github-reusable-pipeline/.github/workflows/springboot.yml@main
    secrets: inherit
    with:
      build-jar: true
      build-image: true
      native-image: false